import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    //flex: 1,
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 16,
    marginTop: 10,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    fontFamily: 'OpenSans-SemiBold',
    marginBottom: 10,
  },
  chart: {
    marginTop: 10,
    width: 300,
    height: 300,
    borderRadius: 10,
    borderWidth: 0,
    borderColor: '#ddd',
  },
  title: {
    marginTop: 10,
    fontSize: 20,
    marginBottom: 10,
    fontSize: 22,
    fontFamily: 'OpenSans-Bold',
    color: '#333',
    fontWeight: 'bold'
  },
  button:{
    marginTop: 20,
    padding: 10,
    backgroundColor: '#D10000',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    marginVertical: 10, 
    shadowColor: '#000',  
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1, 
    color: '#fff',
    shadowRadius: 4,
    fontFamily: 'OpenSans-SemiBold',
    borderWidth: 1,
    borderColor: '#ddd',
    width: '90%',
    alignSelf: 'center',
    elevation: 2,
    marginBottom: 20,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    fontcolor: '#333',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginHorizontal: 10,
    marginVertical: 1,
    padding: 10,
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1, 
    marginTop: 20,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    fontFamily: 'OpenSans-SemiBold',  
    marginBottom: 60,
    width: '90%',
    alignSelf: 'center',
    fontcolor: '#333',
  },
});
